// Nexus — Wallet certification lab data + honest helpers (plan-35 §6).
//
// An OPERATOR/QA surface (not a consumer wallet): it reads a live wallet-lab
// context if served, falling back to the fixture. Every provider row carries its
// certification LEVEL (never just PASS/pending), the latest tested version, its
// caveats, the evidence hash, a verify command, a prompt-readability score, and a
// stale indicator. A PASS/level is only ever shown for a sealed bundle — the lab
// never invents support.

let _data = null;

/** setWalletLabData injects the data (used by the no-browser smoke test). */
export function setWalletLabData(obj) {
  _data = obj;
}

/** getWalletLabData returns the loaded data. */
export function getWalletLabData() {
  if (!_data) throw new Error('wallet-lab: data not loaded — call loadWalletLab() first');
  return _data;
}

/** loadWalletLab fetches a live context if served, falling back to the fixture. */
export async function loadWalletLab(liveUrl = '/v1/wallet-lab/context', fixtureUrl = '/testdata/wallet-lab.fixture.json') {
  try {
    const res = await fetch(liveUrl, { cache: 'no-cache' });
    if (res.ok) {
      _data = await res.json();
      _data._live = true;
      return _data;
    }
  } catch (_) {
    /* no live endpoint — fall back to the fixture */
  }
  const res = await fetch(fixtureUrl, { cache: 'no-cache' });
  if (!res.ok) throw new Error('wallet-lab: failed to load ' + fixtureUrl + ' (' + res.status + ')');
  _data = await res.json();
  _data._live = false;
  return _data;
}

/** isLive reports whether the loaded data came from a live endpoint. */
export function isLive() {
  return !!(_data && _data._live);
}

/** generatedNote is the honest provenance line. */
export function generatedNote() {
  return (_data && _data.generatedNote) ||
    'Generated by `infrix wallet matrix generate` from sealed certification bundles. A level is shown only for a sealed, verified bundle.';
}

/** providers returns the normalised provider rows (never null). */
export function providers() {
  const rows = (_data && _data.providers) || [];
  return rows.map((r) => ({
    provider: r.provider || '—',
    browser: r.browser || '—',
    os: r.os || '—',
    network: r.network || '—',
    level: r.level || 'L0',
    result: r.result || 'pending',
    latestVersion: r.latestVersion || '—',
    evidenceHash: r.evidenceHash || '',
    verifyCommand: r.verifyCommand || '',
    caveats: Array.isArray(r.caveats) ? r.caveats : [],
    promptScore: typeof r.promptScore === 'number' ? r.promptScore : null,
    stale: !!r.stale,
  }));
}

/** certifiedProviders returns only rows that carry a real (L3+) certification
 * backed by an evidence hash — the honest "supported" set. */
export function certifiedProviders() {
  return providers().filter((r) => /^L[3-5]$/.test(r.level) && r.evidenceHash && !r.stale);
}

/** hasOverclaim reports whether any row claims a level without backing evidence
 * (a level L3+ but no evidence hash) — the lab must never show this. */
export function hasOverclaim() {
  return providers().some((r) => /^L[3-5]$/.test(r.level) && !r.evidenceHash);
}
